import { Product } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  // MEN'S COLLECTION
  {
    id: "mzt-men-01",
    title: "Double-Breasted Cashmere Overcoat",
    category: "Men",
    price: 3450,
    image_url: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop",
    description: "An exacting silhouette rendered in double-faced Loro Piana cashmere. Features clean architectural shoulders, concealed horn button placket, and a soft, fluid drape designed for ceremonial elegance.",
    details: "100% Mongolian Cashmere • Viscose Cupro Lining • Handcrafted in Biella, Italy",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mzt-men-02",
    title: "Minimalist Silk Poplin Evening Shirt",
    category: "Men",
    price: 980,
    image_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1200&auto=format&fit=crop",
    description: "Subtle modernism defined by a razor-sharp band collar and hidden mother-of-pearl buttons. Cut from 100% mulberry silk with a matte sheen that reacts gracefully to light.",
    details: "100% Mulberry Silk • Mother-of-Pearl Buttons • Made in France",
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "mzt-men-03",
    title: "Sculptural Gabardine Trench Coat",
    category: "Men",
    price: 2890,
    image_url: "https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=1200&auto=format&fit=crop",
    description: "An homage to modern structuralism. Cut from heavy water-repellent Japanese cotton gabardine, accented with matte gunmetal D-rings and a storm flap silhouette.",
    details: "100% Japanese Cotton Gabardine • Storm Shield Flap • Made in London",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mzt-men-04",
    title: "Polished Box-Calf Chelsea Boot",
    category: "Men",
    price: 1420,
    image_url: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1200&auto=format&fit=crop",
    description: "Formed from whole-cut Parisian box calfskin on an elongated, chiseled last. Goodyear-welted with beveled leather soles hand-painted in obsidian.",
    details: "Full-Grain French Box Calf • Goodyear Welted Sole • Hand-Finished in Florence",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },

  // WOMEN'S COLLECTION
  {
    id: "mzt-women-01",
    title: "Sculptural Draped Silk Wool Gown",
    category: "Women",
    price: 3850,
    image_url: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop",
    description: "A masterwork of bias-cut couture construction. Drapes diagonally across the torso into a column silhouette, evoking ancient Grecian statuary with modern Parisian restraint.",
    details: "70% Silk Twill, 30% Virgin Wool • Invisible Back Zip • High Fashion Studio, Paris",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "mzt-women-02",
    title: "Structured Hourglass Wool Blazer",
    category: "Women",
    price: 2650,
    image_url: "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop",
    description: "Crafted with interior horsehair canvas for an unyielding architectural waist and pronounced peaked lapels. Minimalist single-button closure with discreet jetted pockets.",
    details: "100% Superfine Wool Crepe • Silk Cupro Lining • Tailored in Milan",
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "mzt-women-03",
    title: "The Mozart Monogram Large Bag",
    category: "Women",
    price: 4200,
    image_url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop",
    description: "Sculpted from hand-buffed calf leather with palladium-finish brass hardware. Clean geometrical lines with a microfiber suede interior and dual magnetic latch.",
    details: "Grained Calfskin • Hand-Lacquered Raw Edges • Crafted in Tuscany",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "mzt-women-04",
    title: "Alabaster Cashmere Mock-Neck Knit",
    category: "Women",
    price: 1350,
    image_url: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1200&auto=format&fit=crop",
    secondary_image_url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop",
    description: "Knitted from 4-ply Grade A Mongolian cashmere yarn. Boasts a seamless tubular silhouette with relaxed drop shoulders and refined ribbed collar and cuffs.",
    details: "100% Organic Mongolian Cashmere • Seamless 3D Knit • Made in Scotland",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
